sudo: true
branches:
  only:
  - master
language: python

before_install:
#- openssl aes-256-cbc -K $encrypted_efc81948d3a6_key -iv $encrypted_efc81948d3a6_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- openssl aes-256-cbc -K $encrypted_c9eb939fbec6_key -iv $encrypted_c9eb939fbec6_iv -in publish-key-fabio.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
#- git remote set-url origin git@github.com:pythonbrasil/pythonbrasil12-site.git
- git remote set-url origin git@github.com:luzfcb/pythonbrasil12-site.git
- git fetch origin -f gh-pages:gh-pages

install:
- pip2 install --upgrade pip setuptools
# - pip2 install -r requirements.txt
- pip2 install --upgrade ansible
- sudo make ansible-setup
#add the rest of setup here
script:
- make html

deploy:
  provider: script
  script: make travis ping
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

