sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_c9eb939fbec6_key -iv $encrypted_c9eb939fbec6_iv -in publish-key-fabio.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:luzfcb/pythonbrasil12-site.git
- git fetch origin -f gh-pages:gh-pages

install:
  - gem install sass
  - cd theme
  - npm install -g
  - cd ..
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - make github

deploy:
  provider: script
  script: make travis ping
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

